// ── FILE: js/config.js ─────────────────────────────
export const CONFIG = {
  // Using a placeholder URL as the model isn't provided, but in a real app this would point to the hosted model.json
  MODEL_URL: 'https://storage.googleapis.com/tfjs-models/tfjs/mobilenet_v1_0.25_224/model.json',
  MODEL_IDB_KEY: 'leafscan-mobilenetv3-v1',
  INPUT_SIZE: 224,
  TOP_K: 3,
  CONFIDENCE_THRESHOLD: 0.45,
  WEATHER_API_KEY: '00000000000000000000000000000000', // Placeholder
  WEATHER_CACHE_TTL: 1800000,       // 30 minutes in ms
  HISTORY_MAX_ITEMS: 100,
  PARTICLE_COUNT: 1000,
  PLANT_COUNT: 300,
  FRUIT_COUNT: 20,
  ANIMATION_FPS_CAP: 60,
  DEBOUNCE_SEARCH_MS: 200,
};

export const CLASS_LABELS = [
  'Apple___Apple_scab',
  'Apple___Black_rot',
  'Apple___Cedar_apple_rust',
  'Apple___healthy',
  'Blueberry___healthy',
  'Cherry_(including_sour)___Powdery_mildew',
  'Cherry_(including_sour)___healthy',
  'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot',
  'Corn_(maize)___Common_rust_',
  'Corn_(maize)___Northern_Leaf_Blight',
  'Corn_(maize)___healthy',
  'Grape___Black_rot',
  'Grape___Esca_(Black_Measles)',
  'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)',
  'Grape___healthy',
  'Orange___Haunglongbing_(Citrus_greening)',
  'Peach___Bacterial_spot',
  'Peach___healthy',
  'Pepper,_bell___Bacterial_spot',
  'Pepper,_bell___healthy',
  'Potato___Early_blight',
  'Potato___Late_blight',
  'Potato___healthy',
  'Raspberry___healthy',
  'Soybean___healthy',
  'Squash___Powdery_mildew',
  'Strawberry___Leaf_scorch',
  'Strawberry___healthy',
  'Tomato___Bacterial_spot',
  'Tomato___Early_blight',
  'Tomato___Late_blight',
  'Tomato___Leaf_Mold',
  'Tomato___Septoria_leaf_spot',
  'Tomato___Spider_mites Two-spotted_spider_mite',
  'Tomato___Target_Spot',
  'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
  'Tomato___Tomato_mosaic_virus',
  'Tomato___healthy'
];
